USE [BD3]
GO

CREATE TABLE [dbo].[Personne](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nom] [nvarchar](max) NULL,
	[Ville] [bigint] NULL,
 CONSTRAINT [PK_Personne] PRIMARY KEY CLUSTERED 
(
	[id]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

select * from Personne

